# No version needed in Docker Compose v2
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  server:
    build:
      context: .
      dockerfile: microservice_b/Dockerfile
    container_name: grpc_server
    ports:
      - "1323:1323"
    depends_on:
      - mysql

  client:
    build:
      context: .
      dockerfile: microservice_a/Dockerfile
    container_name: grpc_client
    depends_on:
      - server

volumes:
  mysql_data:
